export const ROLES = {
    ADMINISTRADOR: 'ROLE_ADMINISTRADOR',
    EJECUTIVO_VENTAS: 'ROLE_EJECUTIVO_DE_VENTAS',
    ASISTENTE_RECEPCION: 'ROLE_ASISTENTE_DE_RECEPCION',
    ASISTENTE_TECNICO: 'ROLE_ASISTENTE_TECNICO'
};
